Beta 0.2 - Use cargo-build-bpf instead of anchor build
error: target is not supported, for more information see: https://docs.rs/getrandom/#unsupported-targets
   --> src\lib.rs:267:9
    |
267 | /         compile_error!("\
268 | |             target is not supported, for more information see: \
269 | |             https://docs.rs/getrandom/#unsupported-targets\
270 | |         ");
    | |__________^

error[E0433]: failed to resolve: use of undeclared crate or module `imp`
   --> src\lib.rs:291:5
    |
291 |     imp::getrandom_inner(dest)
    |     ^^^ use of undeclared crate or module `imp`

For more information about this error, try `rustc --explain E0433`.
error: could not compile `getrandom` due to 2 previous errors
warning: build failed, waiting for other jobs to finish...
Error: Function _ZN15crossbeam_epoch8internal6Global8push_bag17h6bf93e49e32c1277E Stack offset of 4104 exceeded max offset of 4096 by 8 bytes, please minimize large stack variables
Error: Function _ZN15crossbeam_epoch8internal6Global7collect17h024a941f9fa1a310E Stack offset of 4200 exceeded max offset of 4096 by 104 bytes, please minimize large stack variables